"""
ROX Proven Edge Engine v3.0 - Trade Logger
=========================================
Dedicated trade logging and reconciliation.
"""

import os
from typing import Dict, List, Optional
from datetime import datetime, date, timedelta
from dataclasses import dataclass, asdict
import csv
import json

from .data_manager import DataManager


@dataclass
class TradeLogEntry:
    """Standard trade log entry"""
    trade_id: str
    date_recommended: str
    stock: str
    direction: str
    entry_price: float
    stop_loss: float
    target_price: float
    risk_reward_ratio: float
    recommending_agents: str
    regime_at_entry: str
    conviction_confidence: int
    position_size: int
    position_value: float
    date_closed: str = ""
    exit_price: float = 0.0
    pnl_amount: float = 0.0
    pnl_pct: float = 0.0
    exit_reason: str = ""


class TradeLogger:
    """
    Trade logging and reconciliation system.
    
    Features:
    - Log trades with all relevant details
    - Track trade outcomes
    - Generate reconciliation reports
    - Calculate agent accuracy
    """
    
    def __init__(self, data_manager: DataManager = None):
        self.data_manager = data_manager or DataManager()
        self.trade_counter = self._get_next_trade_id()
    
    def _get_next_trade_id(self) -> int:
        """Get next trade ID from existing logs"""
        trades = self.data_manager.get_trade_history(limit=1000)
        if not trades:
            return 1
        return len(trades) + 1
    
    def log_new_trade(self, trade_setup: Dict, agents: List[str],
                     regime: str, conviction: int) -> str:
        """
        Log a new trade recommendation.
        
        Args:
            trade_setup: Dict with trade details (stock, direction, entry, SL, target, etc.)
            agents: List of agent names that recommended this trade
            regime: Market regime at entry
            conviction: Conviction score (0-100)
            
        Returns:
            Trade ID
        """
        trade_id = f"T{self.trade_counter:04d}"
        self.trade_counter += 1
        
        entry = TradeLogEntry(
            trade_id=trade_id,
            date_recommended=date.today().isoformat(),
            stock=trade_setup.get('stock', ''),
            direction=trade_setup.get('direction', 'LONG'),
            entry_price=trade_setup.get('entry_price', 0),
            stop_loss=trade_setup.get('stop_loss', 0),
            target_price=trade_setup.get('target_1', trade_setup.get('target_price', 0)),
            risk_reward_ratio=trade_setup.get('risk_reward', 0),
            recommending_agents='|'.join(agents),
            regime_at_entry=regime,
            conviction_confidence=conviction,
            position_size=trade_setup.get('shares', 0),
            position_value=trade_setup.get('position_value', 0)
        )
        
        # Log to CSV
        self.data_manager.log_trade(self._entry_to_record(entry))
        
        return trade_id
    
    def _entry_to_record(self, entry: TradeLogEntry) -> Dict:
        """Convert TradeLogEntry to record dict"""
        return {
            "date_recommended": entry.date_recommended,
            "stock": entry.stock,
            "direction": entry.direction,
            "entry_price": entry.entry_price,
            "stop_loss": entry.stop_loss,
            "target_price": entry.target_price,
            "risk_reward_ratio": entry.risk_reward_ratio,
            "recommending_agents": entry.recommending_agents,
            "regime_at_entry": entry.regime_at_entry,
            "conviction_confidence": entry.conviction_confidence,
            "date_closed": entry.date_closed,
            "exit_price": entry.exit_price,
            "pnl_pct": entry.pnl_pct
        }

    def log_options_trade(
        self,
        options_signal: Dict,
        regime: str,
        conviction: int,
        portfolio_value: float = 0.0,
    ) -> str:
        """
        Log an options (F&O) trade signal generated by OPTIMUS.

        Args:
            options_signal  : Dict from OptionsSignal (as returned by OPTIMUS
                              analysis_details['options_signal']).
            regime          : Market regime string at time of signal.
            conviction      : Conviction score 0-100.
            portfolio_value : Total portfolio value for position-sizing context.

        Returns:
            Trade ID string (e.g. "OT0001").
        """
        import os, csv

        trade_id = f"OT{self.trade_counter:04d}"
        self.trade_counter += 1

        symbol      = options_signal.get("symbol", "")
        expiry      = options_signal.get("expiry_date", "")
        opt_type    = options_signal.get("option_type", "")  # CE / PE
        strategy    = options_signal.get("strategy", "")
        strike      = options_signal.get("strike", 0)
        entry_low   = options_signal.get("entry_range", [0, 0])[0]
        entry_high  = options_signal.get("entry_range", [0, 0])[-1]
        stop_loss   = options_signal.get("stop_loss", 0)
        target_1    = options_signal.get("target_1", 0)
        target_2    = options_signal.get("target_2", 0)
        risk_per_lot= options_signal.get("risk_per_lot", 0)
        rationale   = options_signal.get("rationale", "")
        lots        = options_signal.get("suggested_lots", 1)

        record = {
            "trade_id"          : trade_id,
            "date_recommended"  : date.today().isoformat(),
            "instrument_type"   : "OPTIONS",
            "symbol"            : symbol,
            "expiry_date"       : expiry,
            "option_type"       : opt_type,
            "strategy"          : strategy,
            "strike"            : strike,
            "entry_price_low"   : entry_low,
            "entry_price_high"  : entry_high,
            "stop_loss"         : stop_loss,
            "target_1"          : target_1,
            "target_2"          : target_2,
            "lots"              : lots,
            "risk_per_lot"      : risk_per_lot,
            "total_risk"        : round(risk_per_lot * lots, 2),
            "regime_at_entry"   : regime,
            "conviction"        : conviction,
            "recommending_agent": "OPTIMUS",
            "rationale"         : rationale[:200],
            "date_closed"       : "",
            "exit_price"        : 0.0,
            "pnl_amount"        : 0.0,
            "pnl_pct"           : 0.0,
            "exit_reason"       : "",
        }

        # Write / append to a dedicated options CSV
        from pathlib import Path
        import sys
        sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        try:
            from core.config import DATA_DIR
            options_log_path = DATA_DIR / "options_trades.csv"
        except Exception:
            options_log_path = Path("data/options_trades.csv")
            options_log_path.parent.mkdir(parents=True, exist_ok=True)

        fieldnames = list(record.keys())
        write_header = not options_log_path.exists()

        with open(options_log_path, "a", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=fieldnames)
            if write_header:
                writer.writeheader()
            writer.writerow(record)

        return trade_id
    
    def close_trade(self, trade_id: str, exit_price: float, 
                   exit_reason: str = "") -> bool:
        """
        Close a trade and record outcome.
        
        Args:
            trade_id: Trade ID to close
            exit_price: Exit price
            exit_reason: Reason for exit (target_hit, stop_hit, manual, etc.)
            
        Returns:
            True if successful
        """
        trades = self.data_manager.get_trade_history(limit=500)
        
        for trade in trades:
            # Find by stock and date (trade_id not in CSV format)
            if not trade.get('date_closed'):
                # Calculate P&L
                entry = float(trade['entry_price'])
                direction = trade['direction']
                
                if direction == 'LONG':
                    pnl_pct = (exit_price - entry) / entry * 100
                else:
                    pnl_pct = (entry - exit_price) / entry * 100
                
                # Update in CSV
                success = self.data_manager.update_trade_outcome(
                    trade['stock'],
                    trade['date_recommended'],
                    exit_price,
                    pnl_pct
                )
                
                if success:
                    # Log agent performance
                    agents = trade['recommending_agents'].split('|')
                    correct = pnl_pct > 0
                    
                    for agent in agents:
                        self.data_manager.log_agent_performance(
                            agent_name=agent,
                            prediction=trade['direction'],
                            outcome=f"{'WIN' if correct else 'LOSS'}",
                            correct=correct,
                            regime=trade['regime_at_entry']
                        )
                
                return success
        
        return False
    
    def generate_weekly_reconciliation(self, week_num: int = None) -> str:
        """
        Generate weekly reconciliation report.
        
        Args:
            week_num: Week number (defaults to current week)
            
        Returns:
            Report content as string
        """
        week_num = week_num or date.today().isocalendar()[1]
        
        # Get last 7 days of trades
        trades = self.data_manager.get_trade_history(limit=100)
        
        # Filter to this week
        from datetime import timedelta
        week_start = date.today() - timedelta(days=date.today().weekday())
        week_end = week_start + timedelta(days=6)
        
        week_trades = [
            t for t in trades
            if week_start <= date.fromisoformat(t['date_recommended']) <= week_end
        ]
        
        closed_trades = [t for t in week_trades if t.get('date_closed')]
        
        # Calculate statistics
        wins = sum(1 for t in closed_trades if float(t.get('pnl_pct', 0)) > 0)
        losses = len(closed_trades) - wins
        
        total_return = sum(float(t.get('pnl_pct', 0)) for t in closed_trades)
        
        # Agent accuracy
        agent_accuracy = {}
        for trade in closed_trades:
            agents = trade.get('recommending_agents', '').split('|')
            won = float(trade.get('pnl_pct', 0)) > 0
            
            for agent in agents:
                if agent not in agent_accuracy:
                    agent_accuracy[agent] = {"correct": 0, "total": 0}
                agent_accuracy[agent]["total"] += 1
                if won:
                    agent_accuracy[agent]["correct"] += 1
        
        # Build report
        lines = []
        lines.append(f"WEEKLY RECONCILIATION REPORT - Week {week_num}")
        lines.append(f"Week of: {week_start} to {week_end}")
        lines.append("=" * 50)
        lines.append("")
        
        lines.append("1. TRADE PERFORMANCE")
        lines.append(f"   Total recommendations: {len(week_trades)}")
        lines.append(f"   Closed trades: {len(closed_trades)}")
        lines.append(f"   Winning trades: {wins} ({wins/len(closed_trades)*100 if closed_trades else 0:.1f}%)")
        lines.append(f"   Losing trades: {losses} ({losses/len(closed_trades)*100 if closed_trades else 0:.1f}%)")
        lines.append(f"   Total return: {total_return:.2f}%")
        lines.append("")
        
        lines.append("2. AGENT ACCURACY TABLE")
        lines.append("   Agent    | Correct | Total | Accuracy")
        lines.append("   " + "-" * 40)
        for agent, stats in sorted(agent_accuracy.items()):
            acc = stats["correct"] / stats["total"] * 100 if stats["total"] > 0 else 0
            lines.append(f"   {agent:9}| {stats['correct']:7}| {stats['total']:5}| {acc:.1f}%")
        lines.append("")
        
        lines.append("3. RECOMMENDED WEIGHT ADJUSTMENTS")
        for agent, stats in sorted(agent_accuracy.items()):
            acc = stats["correct"] / stats["total"] if stats["total"] > 0 else 0.5
            if acc > 0.65:
                lines.append(f"   {agent}: Increase weight (+3%)")
            elif acc < 0.45:
                lines.append(f"   {agent}: Decrease weight (-3%)")
            else:
                lines.append(f"   {agent}: Maintain current weight")
        lines.append("")
        
        lines.append("4. KEY LEARNINGS")
        lines.append("   - [Add observations from the week's trades]")
        lines.append("")
        
        lines.append("5. NEXT WEEK ADJUSTMENTS")
        lines.append("   - [Specific changes to implement]")
        
        report = "\n".join(lines)
        
        # Save report
        self.data_manager.save_weekly_reconciliation(week_num, report)
        
        return report
    
    def get_open_trades(self) -> List[Dict]:
        """Get all currently open trades"""
        trades = self.data_manager.get_trade_history(limit=100)
        return [t for t in trades if not t.get('date_closed')]
    
    def calculate_portfolio_heat(self) -> float:
        """Calculate current portfolio heat (total risk %)"""
        open_trades = self.get_open_trades()
        
        total_risk = 0
        for trade in open_trades:
            entry = float(trade.get('entry_price', 0))
            sl = float(trade.get('stop_loss', 0))
            position_value = float(trade.get('position_value', 100000))  # Default
            
            if entry > 0 and sl > 0:
                risk_per_share = abs(entry - sl)
                # Estimate shares from position value
                shares = position_value / entry if entry > 0 else 0
                risk_amount = risk_per_share * shares
                
                # Assume 10L portfolio for percentage
                total_risk += risk_amount / 1000000 * 100
        
        return total_risk
    
    def check_trade_allowed(self, new_risk_pct: float, 
                           max_heat: float = 8.0) -> bool:
        """Check if a new trade would exceed portfolio heat limit"""
        current_heat = self.calculate_portfolio_heat()
        return (current_heat + new_risk_pct) <= max_heat


# ===========================================================================
# ENHANCEMENT: Continuous Learning Module
# Feedback loop, pattern accuracy tracking, weight adjustment, seasonality
# ===========================================================================

import math as _math
from collections import defaultdict as _defaultdict


class ContinuousLearningModule:
    """
    ROX Continuous Learning Module
    ================================
    Closes the feedback loop between predictions and market outcomes.

    Capabilities
    ------------
    1. Prediction Accuracy Tracking  – per-agent win/loss/accuracy over time
    2. Winning/Losing Pattern Analysis – identifies which setups work best
    3. Regime-Adaptive Weight Adjustment – boosts agents that excel in current regime
    4. Seasonality Analysis – Budget month, result seasons, F&O expiry effects
    """

    # Regime tags for classification
    REGIME_LABELS = ["BULL", "BEAR", "CONSOLIDATION", "HIGH_VOLATILITY"]

    # Seasonal calendar (month -> context)
    SEASONAL_CALENDAR = {
        1:  {"label": "Budget Month",        "bias": "VOLATILE",   "note": "Pre-budget rally / sell-off"},
        2:  {"label": "Budget Aftermath",    "bias": "TRENDING",   "note": "Post-budget trend establishment"},
        3:  {"label": "Q3 Results",          "bias": "STOCK_PICK", "note": "Q3 earnings season"},
        4:  {"label": "FY End / New FY",     "bias": "VOLATILE",   "note": "Mutual fund rebalancing, advance tax"},
        5:  {"label": "Q4 Results",          "bias": "STOCK_PICK", "note": "Full-year results, dividend announcements"},
        6:  {"label": "Pre-Monsoon",         "bias": "NEUTRAL",    "note": "Monsoon forecast impact on FMCG/Agro"},
        7:  {"label": "Q1 Results",          "bias": "STOCK_PICK", "note": "Q1 earnings season"},
        8:  {"label": "Monsoon Mid",         "bias": "NEUTRAL",    "note": "Sector rotation: Pharma, Cement"},
        9:  {"label": "FII Rebalancing",     "bias": "VOLATILE",   "note": "Global fund rebalancing, DII flows"},
        10: {"label": "Q2 Results",          "bias": "STOCK_PICK", "note": "Q2 earnings + Diwali rally"},
        11: {"label": "Diwali / FII Flows",  "bias": "BULLISH",    "note": "Historically strong month"},
        12: {"label": "Year-End Drift",      "bias": "LOW_VOL",    "note": "Holiday thin-volumes, tax harvesting"},
    }

    # F&O expiry effect window (days before expiry where volatility picks up)
    FNO_EXPIRY_ALERT_DAYS = 5

    def __init__(self, trade_logger: 'TradeLogger'):
        self.trade_logger = trade_logger
        self.logger = __import__('logging').getLogger("ContinuousLearning")

        # In-memory accuracy store: {agent: {regime: {wins, total}}}
        self._accuracy_store: dict = _defaultdict(
            lambda: _defaultdict(lambda: {"wins": 0, "total": 0, "pnl_sum": 0.0})
        )

        # Pattern success tracker: {pattern_name: {wins, total}}
        self._pattern_store: dict = _defaultdict(lambda: {"wins": 0, "total": 0, "avg_pnl": 0.0})

        # Weight history for explainability
        self._weight_history: list = []

        # Load from trade history on init
        self._bootstrap_from_history()

    # ------------------------------------------------------------------
    # 1. Prediction Accuracy Feedback Loop
    # ------------------------------------------------------------------

    def record_outcome(self, trade_record: dict):
        """
        Record a closed trade outcome into the learning store.

        trade_record keys:
            stock, direction, recommending_agents (pipe-separated), regime_at_entry,
            conviction_confidence, pnl_pct, exit_reason, pattern (optional)
        """
        pnl = float(trade_record.get("pnl_pct", 0.0))
        won = pnl > 0
        regime = trade_record.get("regime_at_entry", "UNKNOWN").upper()
        agents = [a.strip() for a in trade_record.get("recommending_agents", "").split("|") if a.strip()]
        pattern = trade_record.get("pattern", "")

        for agent in agents:
            store = self._accuracy_store[agent][regime]
            store["total"] += 1
            store["pnl_sum"] += pnl
            if won:
                store["wins"] += 1

        if pattern:
            ps = self._pattern_store[pattern]
            ps["total"] += 1
            ps["avg_pnl"] = (ps["avg_pnl"] * (ps["total"] - 1) + pnl) / ps["total"]
            if won:
                ps["wins"] += 1

        self.logger.debug(f"Outcome recorded: {trade_record.get('stock')} | "
                          f"P&L: {pnl:.2f}% | Won: {won}")

    def get_agent_accuracy(self, agent: str, regime: str = None) -> dict:
        """
        Returns accuracy stats for an agent, optionally filtered by regime.
        """
        if regime:
            data = self._accuracy_store[agent].get(regime.upper(), {"wins": 0, "total": 0, "pnl_sum": 0.0})
            total = data["total"]
            wins = data["wins"]
            return {
                "agent": agent,
                "regime": regime,
                "wins": wins,
                "total": total,
                "accuracy_pct": round(wins / total * 100, 1) if total else 0,
                "avg_pnl_pct": round(data["pnl_sum"] / total, 2) if total else 0,
            }

        # Aggregate across all regimes
        all_wins = sum(d["wins"] for d in self._accuracy_store[agent].values())
        all_total = sum(d["total"] for d in self._accuracy_store[agent].values())
        all_pnl = sum(d["pnl_sum"] for d in self._accuracy_store[agent].values())
        return {
            "agent": agent,
            "regime": "ALL",
            "wins": all_wins,
            "total": all_total,
            "accuracy_pct": round(all_wins / all_total * 100, 1) if all_total else 0,
            "avg_pnl_pct": round(all_pnl / all_total, 2) if all_total else 0,
        }

    def print_accuracy_matrix(self) -> str:
        """Formatted accuracy matrix across agents and regimes."""
        agents = sorted(self._accuracy_store.keys())
        regimes = self.REGIME_LABELS
        lines = ["PREDICTION ACCURACY MATRIX", "-" * 70]
        header = f"{'Agent':<12}" + "".join(f"{r:>18}" for r in regimes)
        lines.append(header)
        lines.append("-" * 70)
        for agent in agents:
            row = f"{agent:<12}"
            for regime in regimes:
                stats = self.get_agent_accuracy(agent, regime)
                if stats["total"] > 0:
                    row += f"  {stats['accuracy_pct']:>5.1f}% ({stats['total']:>3})"
                else:
                    row += f"{'—':>18}"
            lines.append(row)
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 2. Winning / Losing Pattern Analysis
    # ------------------------------------------------------------------

    def analyze_patterns(self, min_sample: int = 5) -> list:
        """
        Returns a ranked list of patterns by win-rate (minimum sample enforced).
        Each entry: {pattern, win_rate, avg_pnl, total_trades}
        """
        results = []
        for pattern, stats in self._pattern_store.items():
            if stats["total"] < min_sample:
                continue
            win_rate = stats["wins"] / stats["total"]
            results.append({
                "pattern": pattern,
                "win_rate_pct": round(win_rate * 100, 1),
                "avg_pnl_pct": round(stats["avg_pnl"], 2),
                "total_trades": stats["total"],
            })
        results.sort(key=lambda x: x["win_rate_pct"], reverse=True)
        return results

    def get_best_patterns(self, top_n: int = 5) -> list:
        return self.analyze_patterns()[:top_n]

    def get_worst_patterns(self, top_n: int = 5) -> list:
        return self.analyze_patterns()[-top_n:]

    def pattern_analysis_report(self) -> str:
        patterns = self.analyze_patterns()
        lines = ["PATTERN PERFORMANCE ANALYSIS", "-" * 55]
        lines.append(f"{'Pattern':<30} {'Win%':>6} {'AvgPnL%':>8} {'Trades':>6}")
        lines.append("-" * 55)
        for p in patterns:
            lines.append(
                f"{p['pattern']:<30} {p['win_rate_pct']:>5.1f}% "
                f"{p['avg_pnl_pct']:>+7.2f}% {p['total_trades']:>6}"
            )
        if not patterns:
            lines.append("  Insufficient data (min 5 trades per pattern required)")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 3. Regime-Adaptive Weight Adjustment
    # ------------------------------------------------------------------

    def compute_weight_adjustments(self, current_regime: str,
                                   base_weights: dict,
                                   min_weight: float = 0.05,
                                   max_weight: float = 0.35,
                                   learning_rate: float = 0.03) -> dict:
        """
        Compute updated agent weights based on historical accuracy in the
        current market regime. High-accuracy agents get a boost; poor-
        accuracy agents get trimmed. Uses bounded gradient nudge.

        Parameters
        ----------
        current_regime  : str   – e.g. "BULL"
        base_weights    : dict  – {agent_name: current_weight (0–1)}
        learning_rate   : float – how aggressively to adjust (default 3%)

        Returns
        -------
        dict – {agent_name: new_weight}
        """
        regime = current_regime.upper()
        adjustments = {}

        total_weight = sum(base_weights.values()) or 1.0

        for agent, weight in base_weights.items():
            stats = self.get_agent_accuracy(agent, regime)
            total_trades = stats["total"]

            if total_trades < 5:
                # Not enough data – keep existing weight
                adjustments[agent] = weight
                continue

            accuracy = stats["accuracy_pct"] / 100.0

            # Delta: positive for high accuracy, negative for low
            delta = (accuracy - 0.5) * learning_rate * 2
            new_weight = max(min_weight, min(max_weight, weight + delta))
            adjustments[agent] = round(new_weight, 4)

        # Normalize so weights sum to 1.0
        total = sum(adjustments.values()) or 1.0
        normalized = {k: round(v / total, 4) for k, v in adjustments.items()}

        # Log adjustment event
        self._weight_history.append({
            "timestamp": __import__('datetime').datetime.now().isoformat(),
            "regime": regime,
            "weights": normalized,
        })

        self.logger.info(f"Weight adjustments computed for regime={regime}: {normalized}")
        return normalized

    def weight_adjustment_report(self, current_regime: str, base_weights: dict) -> str:
        new_weights = self.compute_weight_adjustments(current_regime, base_weights)
        lines = [f"WEIGHT ADJUSTMENT REPORT — Regime: {current_regime}", "-" * 50]
        lines.append(f"{'Agent':<12} {'Old Weight':>12} {'New Weight':>12} {'Delta':>10}")
        lines.append("-" * 50)
        for agent, new_w in sorted(new_weights.items()):
            old_w = base_weights.get(agent, 0.0)
            delta = new_w - old_w
            sign = "▲" if delta > 0 else ("▼" if delta < 0 else "─")
            lines.append(f"{agent:<12} {old_w:>11.3f}  {new_w:>11.3f}  {sign}{abs(delta):.3f}")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 4. Seasonality Analysis
    # ------------------------------------------------------------------

    def get_seasonality_context(self, dt: 'date' = None) -> dict:
        """
        Return the current seasonal trading context:
        month label, market bias, and F&O expiry proximity.

        dt: date object (defaults to today)
        """
        from datetime import date, timedelta
        if dt is None:
            dt = date.today()

        month_info = self.SEASONAL_CALENDAR.get(dt.month, {
            "label": "Unknown", "bias": "NEUTRAL", "note": ""
        })

        # F&O expiry: last Thursday of each month
        fno_expiry = self._last_thursday_of_month(dt.year, dt.month)
        days_to_expiry = (fno_expiry - dt).days
        near_expiry = 0 <= days_to_expiry <= self.FNO_EXPIRY_ALERT_DAYS

        return {
            "date": dt.isoformat(),
            "month": dt.month,
            "month_label": month_info["label"],
            "seasonal_bias": month_info["bias"],
            "seasonal_note": month_info["note"],
            "fno_expiry_date": fno_expiry.isoformat(),
            "days_to_fno_expiry": days_to_expiry,
            "near_fno_expiry": near_expiry,
            "expiry_alert": (
                f"⚠️ F&O expiry in {days_to_expiry} day(s) — expect elevated IV/premium decay"
                if near_expiry else ""
            ),
        }

    @staticmethod
    def _last_thursday_of_month(year: int, month: int) -> 'date':
        """Return the last Thursday (weekday=3) of a given month."""
        from datetime import date
        import calendar
        last_day = calendar.monthrange(year, month)[1]
        for day in range(last_day, last_day - 7, -1):
            if date(year, month, day).weekday() == 3:  # Thursday
                return date(year, month, day)
        return date(year, month, last_day)

    def seasonality_report(self) -> str:
        ctx = self.get_seasonality_context()
        lines = [
            "SEASONALITY ANALYSIS",
            "-" * 45,
            f"  Date           : {ctx['date']}",
            f"  Month Theme    : {ctx['month_label']}",
            f"  Seasonal Bias  : {ctx['seasonal_bias']}",
            f"  Note           : {ctx['seasonal_note']}",
            f"  F&O Expiry     : {ctx['fno_expiry_date']} (T-{ctx['days_to_fno_expiry']}d)",
        ]
        if ctx["expiry_alert"]:
            lines.append(f"  {ctx['expiry_alert']}")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Full Learning Report
    # ------------------------------------------------------------------

    def full_learning_report(self, current_regime: str = "BULL",
                              base_weights: dict = None) -> str:
        base_weights = base_weights or {}
        sections = [
            "=" * 65,
            "ROX CONTINUOUS LEARNING MODULE — FULL REPORT",
            f"Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "=" * 65,
            "",
            self.seasonality_report(),
            "",
            self.print_accuracy_matrix(),
            "",
            self.pattern_analysis_report(),
        ]
        if base_weights:
            sections += ["", self.weight_adjustment_report(current_regime, base_weights)]
        sections += ["", "=" * 65]
        return "\n".join(sections)

    # ------------------------------------------------------------------
    # Bootstrap from existing trade history
    # ------------------------------------------------------------------

    def _bootstrap_from_history(self):
        """Load closed trade outcomes into the accuracy store on startup."""
        try:
            trades = self.trade_logger.data_manager.get_trade_history(limit=500)
            closed = [t for t in trades if t.get("date_closed") and t.get("pnl_pct") is not None]
            for trade in closed:
                self.record_outcome(trade)
            if closed:
                self.logger.info(f"Bootstrapped {len(closed)} historical outcomes into learning module")
        except Exception as e:
            self.logger.warning(f"Could not bootstrap learning module: {e}")
