"""ROX Engine v5.0 — Data Classes for Pipeline"""
from dataclasses import dataclass, field
from typing import Optional
from enum import Enum


class SignalDirection(Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class SignalStrength(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    STRONG = "STRONG"


@dataclass
class Signal:
    """A trading signal generated by an agent."""
    symbol: str
    direction: SignalDirection
    strength: SignalStrength
    agent: str
    rr_ratio: float = 0.0
    rsi: Optional[float] = None
    volume: Optional[float] = None
    volume_avg_20d: Optional[float] = None
    price: Optional[float] = None
    sma_20: Optional[float] = None
    sma_50: Optional[float] = None
    sma_200: Optional[float] = None
    sector: str = ""
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    target_1: Optional[float] = None
    target_2: Optional[float] = None
    position_size: int = 0
    risk_amount: float = 0.0
    expected_reward: float = 0.0
    metadata: dict = field(default_factory=dict)


@dataclass
class RegimeResult:
    """Result from the regime detection module."""
    regime: str  # BULLISH, BEARISH, CONSOLIDATION, etc.
    confidence: float
    key_level: float
    key_level_type: str  # support, resistance
    reasoning: dict = field(default_factory=dict)
    shift_probability: dict = field(default_factory=dict)
    timestamp: str = ""


@dataclass
class NewsResult:
    """Result from the news impact analysis module."""
    sentiment_score: float  # -100 to +100
    sentiment_label: str
    headline_analysis: list = field(default_factory=list)
    block_long_sectors: list = field(default_factory=list)
    block_short_sectors: list = field(default_factory=list)
    boost_sectors: list = field(default_factory=list)
    uncertainty_level: str = "LOW"
    restrictions: dict = field(default_factory=dict)


@dataclass
class TradePlan:
    """A complete trade plan from the Trading Planner."""
    symbol: str
    direction: str
    entry_price: float
    stop_loss: float
    target_1: float
    target_2: float
    position_size: int
    risk_amount: float
    expected_reward: float
    verdict: str  # EXECUTE, HOLD, SKIP
    verdict_reason: str
    strategy: str
    validation: str
    invalidation: str


@dataclass
class PortfolioState:
    """Current portfolio state."""
    capital: float = 10_00_000.0
    deployed_capital: float = 0.0
    active_positions: list = field(default_factory=list)
    daily_pnl: float = 0.0
    total_trades: int = 0
    winning_trades: int = 0
    winning_pct: float = 0.0


@dataclass
class TradeRecord:
    """Record of a completed trade for self-reflection."""
    id: str
    symbol: str
    direction: str
    entry: float
    entry_time: str
    exit: float
    exit_time: str
    pnl: float
    pnl_pct: float
    confidence: float
    reasoning: str
    market_before: dict = field(default_factory=dict)
    market_after: dict = field(default_factory=dict)
    outcome: str = "PENDING"
    created_at: str = ""


@dataclass
class MarketState:
    """Complete current market state snapshot."""
    nifty_price: float = 0.0
    nifty_change_pct: float = 0.0
    vix: float = 0.0
    vix_change_pct: float = 0.0
    usd_inr: float = 0.0
    crude_oil: float = 0.0
    gold: float = 0.0
    us_10y_yield: float = 0.0
    
    # DMA positions
    nifty_vs_20dma: float = 0.0
    nifty_vs_50dma: float = 0.0
    nifty_vs_200dma: float = 0.0
    
    # Technical indicators
    rsi_14: float = 0.0
    macd_line: float = 0.0
    macd_signal: float = 0.0
    macd_histogram: float = 0.0
    
    # Institutional flow
    fii_net_cr: float = 0.0
    dii_net_cr: float = 0.0
    fii_trend_days: int = 0
    
    # Options
    pcr: float = 1.0
    max_pain: float = 0.0
    atm_iv: float = 0.0
    iv_skew: float = 1.0
    days_to_expiry: int = 0
    
    # Regime
    regime: str = "UNKNOWN"
    regime_confidence: float = 0.0
    
    # Heatmap data
    heatmap: list = field(default_factory=list)
    sector_rotation: dict = field(default_factory=dict)
    
    # News
    news_sentiment: float = 0.0
    news_restrictions: dict = field(default_factory=dict)
    
    # Raw data for LLM prompts
    raw_market_data: dict = field(default_factory=dict)
    raw_options_chain: dict = field(default_factory=dict)
